apiVersion: v1
kind: Pod
metadata:
  name: pod-name-to-replace
  namespace: pod-namespace-to-replace
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - image: pod-image-to-replace
      name: reproducible-container
      imagePullPolicy: Always
      env:
        - name: IRODS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: irods-password
              key: irods-password
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: name-to-replace
              key: git-password
        - name: RUN_MODE
          value: value-to-replace
      volumeMounts:
        - name: workflow-descriptor
          mountPath: "/app/config"
          readOnly: false
  imagePullSecrets:
    - name: thimo-secret
  volumes:
    - name: workflow-descriptor
      configMap:
        name: config-map-name-to-replace



